#4435: added auto version generation by using bb-gitversion
elbb/bb-buildingblock pull request #2
Opened 2020-02-28 16:21 UTC by FlorianReinhold

2020-03-02 08:38 UTC, siredmar requested changes
Always start with a capital letter for new sentences.

2020-03-02 09:03 UTC, siredmar requested changes
Several findings

2020-03-02 09:03 UTC, siredmar commented on dobi.yaml
> +    description: "-> generate version informations (auto called by dobi.sh)"
Maybe it's worth to eliminate the annotations for versioning, because those are called implicit by dobi.sh.
Does the user need to call them in a seperate step? If not, we could remove those annotations from the user.

2020-03-02 09:03 UTC, siredmar commented on README.md
> +version informations are generated automatically from git history by using gitversion (<https://github.com/elbb/bb-gitversion>).
Always start with a capital letter beginning a new sentence.
Begin Headings with a capital letter.

2020-03-02 09:03 UTC, siredmar commented on README.md
> +version informations are generated automatically from git history by using gitversion (<https://github.com/elbb/bb-gitversion>).
Maybe we can refer explicitly by the name `building block bb-gitversion`
e.g. `version informations are generated automatically from git history by using building block bb-gitversion (https://github.com/elbb/bb-gitversion)`

2020-03-02 09:03 UTC, siredmar commented on README.md
> +version informations are generated automatically from git history by using gitversion (<https://github.com/elbb/bb-gitversion>).
remove < and > signs with url

2020-03-02 09:03 UTC, siredmar commented on meta.yaml
> +  annotations:
see above. maybe we can hide this information because it is run implicitly by dobi.sh

2020-03-02 09:03 UTC, siredmar commented on version.yaml
> +  read-only: false
add comment `# needs to be read/write to work correctly!`

2020-03-02 09:03 UTC, siredmar commented on version.yaml
> +  read-only: false # needs to be read/write to work correctly!!!
remove two ! from !!!

2020-03-02 09:03 UTC, siredmar commented on README.md
>  embedded linux building block's is a project to create reusable and
`embedded linux building block's`
remove `'` -> `embedded linux building blocks`

2020-03-02 09:03 UTC, siredmar commented on README.md
> +version informations are generated automatically from git history by using gitversion (<https://github.com/elbb/bb-gitversion>).
Refactor line 10: 
By default three dobi resou**r**ces are **pre**defined (but not implemented):

2020-03-02 16:33 UTC, FlorianReinhold commented on README.md
> +version informations are generated automatically from git history by using gitversion (<https://github.com/elbb/bb-gitversion>).
Markdown Lint says i have to add brackets.

2020-03-02 16:38 UTC, FlorianReinhold commented on dobi.yaml
> +    description: "-> generate version informations (auto called by dobi.sh)"
in my opionion, it's more clean and explicit to add this annotation.

2020-03-02 16:40 UTC, FlorianReinhold commented on meta.yaml
> +  annotations:
if it's okay for you, I'd keep it that way.

2020-03-02 16:42 UTC, FlorianReinhold commented on version.yaml
> +  read-only: false
i think, its clear enough, that a build needs write access to a gen folder (in contrast to source-dir).

2020-03-03 07:43 UTC, siredmar commented on dobi.yaml
> +    description: "-> generate version informations (auto called by dobi.sh)"
Explicit it is.

2020-03-03 07:44 UTC, siredmar approved these changes

2020-03-03 08:22 UTC, merged