#29: fixed #34: add email and ms teams infos
elbb/bb-buildingblock pull request #35
Opened 2020-10-02 13:44 UTC by JoergZeidler

2020-10-05 07:13 UTC, mlilien requested changes

2020-10-05 07:13 UTC, mlilien commented on README_CICD_INTEGRATION.md
> +The provided pipeline.yaml file demonstrate the usage of email notification.
demonstrate -> demonstrates

2020-10-05 07:13 UTC, mlilien commented on README_CICD_INTEGRATION.md
> +The concourse ci environment automatically could send an e-mail notification about the current build status.
The concourse ci environment can automatically send ...

2020-10-05 07:48 UTC, siredmar commented
@JoergZeidler i guess putting the settings for `email_smtp_pw` and `email_to` in a seperate and gitignored yaml file would be a good idea to avoid getting your smtp password stored in git. Also it would be useful to gitignore the files `email.yaml` and `msteams.yaml`

2020-10-05 12:02 UTC, JoergZeidler commented
@siredmar: thx for the hint about the gitignore. Your proposal about extra file for email settings is already described in the readme ci.

2020-10-06 08:17 UTC, mlilien approved these changes

2020-10-07 10:48 UTC, merged